# Kernel SVM + Iris Dataset

# Using RBF, Polynomial and Sigmoid Kernels in sklearn to implement KSVM

In [ ]:
#Implementing Kernel SVM with Scikit-Learn
#Implementing Kernel SVM with Scikit-Learn is similar to the simple SVM. 
#We will use the famous Iris dataset to predict the category to which a plant belongs based on four attributes: 
#sepal-width, sepal-length, petal-width and petal-length.

#The dataset can be downloaded from the following link:

#https://archive.ics.uci.edu/ml/datasets/iris4

#The rest of the steps are typical machine learning steps and need very little explanation 
#until we reach the part where we train our Kernel SVM.

In [1]:
#Importing Libraries:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the Dataset:

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [3]:
#Assigning targets and features:

X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [4]:
#Train Test Split of data:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
#Training the Algorithm
#To train the kernel SVM, we use the same SVC class of the Scikit-Learn's svm library. 
#The difference lies in the value for the kernel parameter of the SVC class. 
#In the case of the simple SVM we used "linear" as the value for the kernel parameter. 
#However, for kernel SVM you can use Gaussian, polynomial, sigmoid, or computable kernel. 

#We will implement polynomial, Gaussian (RBF), and sigmoid kernels to see which one works better for our problem.



# Case 1: Polynomial Kernel

In [ ]:
#Case 1. Polynomial Kernel
#In the case of polynomial kernel, you also have to pass a value for the degree parameter of the SVC class. 
#This basically is the degree of the polynomial (which helps you adjust the cmplexity of the polynomial kernel)

#As you increase the complexity (or degree of the polynomial of the kernel). What would you think will happen? 
#Explanation: Increasing the complexity of the data would make the algorithm overfit the data 
#by having a highly non-linear boundary


#Take a look at how we can use a polynomial kernel to implement kernel SVM:

In [14]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [15]:
#Making Predictions
#Now once we have trained the algorithm, the next step is to make predictions on the test data.

#Execute the following script to make predictions:

y_pred = svclassifier.predict(X_test)

In [16]:
#Evaluating the Algorithm
#As usual, the final step of any machine learning algorithm is to make evaluations for polynomial kernel. 
#Execute the following script:

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [ ]:
#The output for the kernel SVM using polynomial kernel looks like the output above:

In [ ]:
#Now let's repeat the same steps for Gaussian and sigmoid kernels.



# Case 2: Gaussian (a.k.a RBF) Kernel

In [ ]:
#2. Gaussian Kernel
#Take a look at how we can use polynomial kernel to implement kernel SVM:

In [17]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [ ]:
#To use Gaussian kernel, you have to specify 'rbf' as value for the Kernel parameter of the SVC class.



In [18]:
#Prediction and Evaluation

y_pred = svclassifier.predict(X_test)

In [19]:
#Evaluating the Algorithm
#As usual, the final step of any machine learning algorithm is to make evaluations for the Gaussian (RBF) kernel. 
#Execute the following script:


from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.82      1.00      0.90         9
 Iris-virginica       1.00      0.82      0.90        11

       accuracy                           0.93        30
      macro avg       0.94      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



In [ ]:
#The output of the Kernel SVM with Gaussian kernel looks like the output above:

# Case 3: Sigmoid Kernel

In [ ]:
#3. Sigmoid Kernel
#Finally, let's use a sigmoid kernel for implementing Kernel SVM. Take a look at the following script:


In [11]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [ ]:
#To use the sigmoid kernel, you have to specify 'sigmoid' as value for the kernel parameter of the SVC class.

In [12]:
#Prediction and Evaluation:

y_pred = svclassifier.predict(X_test)

In [13]:
#Evaluating the Algorithm
#As usual, the final step of any machine learning algorithm is to make evaluations for the Sigmoid kernel. 
#Execute the following script:

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        10
Iris-versicolor       0.30      1.00      0.46         9
 Iris-virginica       0.00      0.00      0.00        11

       accuracy                           0.30        30
      macro avg       0.10      0.33      0.15        30
   weighted avg       0.09      0.30      0.14        30



C:\Users\abiy3759\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\abiy3759\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\abiy3759\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#The output of the Kernel SVM with Sigmoid kernel looks like the output above:

# Comparing Kernel Performance: Case 1 vs. Case 2 vs. Case 3

In [ ]:
#Comparison of Kernel Performance

#If we compare the performance of the different types of kernels we can clearly see that the sigmoid kernel performs the worst.
#This is due to the reason that sigmoid function returns two values, 0 and 1, therefore it is more suitable 
#for binary classification problems. However, in our case we had three output classes.

#Amongst the Gaussian kernel and polynomial kernel, we can see that Gaussian kernel achieved a near 100% prediction rate 
#while polynomial kernel misclassified one instance. 
#Therefore the Gaussian kernel performed slightly better. 


#However, there is no hard and fast rule as to which kernel performs best in every scenario. 
#It is all about testing all the kernels and selecting the one with the best results on your test dataset.