In [ ]:
#Diagonal matrix

#A diagonal matrix is one where the values outside the main diagonal
# is taken from the top left of the matrix to the bottom right

#Diagonal matrices consist of mostly zeros and have non-zero
# entries only along the main diagonal

#NumPy provides the function diag() that can create a diagonal
#matrix ( or transform a given vector into a diagonal matrix)

#The example below defines a 3 x 3 square matrix, extracts the 
#main diagonal as a vector, and then creates a diagonal
#matrix from the extracted vector



from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

In [ ]:
#A diagonal matrix (or an original matrix) does not have to be square.



from numpy import array
from numpy import diag
# define square matrix
G = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3],
[6, 7, 2]])
print(G)

# extract diagonal vector
d = diag(G)
print(d)

# create diagonal matrix from vector
D = diag(d)
print(D)

# Example: Using Python to solve a system of linear equations Ax = b

In [1]:
import numpy as np
# define matrix A using Numpy arrays
A = np.array([[2, 1, 1],
 [1, 3, 2],
 [1, 0, 0]]) 

#define matrix B
B = np.array([4, 5, 6]) 

# linalg.solve is the function of NumPy to solve a system of linear scalar equations
print ("Solutions:\n",np.linalg.solve(A, B ))


Solutions:
 [  6.  15. -23.]


# Example: LU Decomposition

In [2]:
# LU decomposition
from numpy import array
from scipy.linalg import lu #remember to load this
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


print(A)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# factorize matrix
P, L, U = lu(A)

In [4]:
print(P)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [5]:
print(L)

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


In [6]:
print(U)

[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [7]:
# reconstruct original matrix 
B = P.dot(L).dot(U)
print(B)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Example: QR decomposition

In [8]:
#Example: QR decomposition

from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])

print(A)


[[1 2]
 [3 4]
 [5 6]]


In [9]:
# factorize original matrix
Q, R = qr(A, 'complete')

In [10]:
print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [11]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [12]:
# reconstruct original matrix from factors Q and R
B = Q.dot(R)

In [13]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Example: Cholesky Decomposition

In [14]:
#Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky

# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)


[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [15]:
# factorize original matrix
L = cholesky(A)


In [16]:
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [17]:
# reconstruct original matrix from factors
B = L.dot(L.T)


In [18]:
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# Example - Eigendecomposition

In [19]:
#eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# factorize original matrix into eigenvalues and eigenvectors
values, vectors = eig(A)


In [21]:
print(values)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [22]:
print(vectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Confirming an Eigenvector and Eigenvalue

In [ ]:
#We can confirm that a vector is an eigenvector of a matrix

#We do this by multiplying the candidate eigenvector by the
#value vector and compare the result with the eigenvalue


In [23]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig


#Step 1: define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


In [24]:
#Step 2: factorize matrix to obtain eigenvalues and eigenvectors
values, vectors = eig(A)


In [25]:
print(values) #print eigenvalues

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [26]:
print(vectors)#print eigenvectors

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [28]:
print(vectors[:,0]) #print first eigenvector

[-0.23197069 -0.52532209 -0.8186735 ]


In [27]:
#Step 3: confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)


[ -3.73863537  -8.46653421 -13.19443305]


In [29]:
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
#The example above multiplies the original matrix with
# the first eigenvector and compares it to the first
# eigenvector multiplied by the first eigenvalue

#Running the example prints the results of these two
#multiplications - and we see that they are equal

In [ ]:
#Reconstruct original matrix

#We can reverse the process and reconstruct the original matrix
#given only the eigenvectors and eigenvalues

In [30]:
#reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# factorize original matrix
values, vectors = eig(A)


In [32]:
# create matrix from eigenvectors
Q = vectors


In [33]:
# create inverse of eigenvectors matrix
R = inv(Q)


In [34]:
# create diagonal matrix from eigenvalues
L = diag(values)


In [35]:
# reconstruct the original matrix
B = Q.dot(L).dot(R)


In [36]:
print(B)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Singular-Value Decomposition

In [37]:
#singular-value decomposition
from numpy import array
from scipy.linalg import svd

# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])

print(A)


[[1 2]
 [3 4]
 [5 6]]


In [38]:
# factorize original matrix using svd()
U, s, V = svd(A)


In [39]:
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [40]:
print(s)

[9.52551809 0.51430058]


In [41]:
print(V)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
#Reconstruct original matrix from factors

In [ ]:
#reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])

print(A)

In [ ]:
# factorize original matrix
U, s, V = svd(A)


In [ ]:
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))


In [ ]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)


In [ ]:
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)


In [ ]:
#The U, s and V elements from svd() cannot be multiplied directly to 
# reconstruct the original matrix

#The s vector must be converted into a diagonal matrix using the
#diag() function. By default, diag() creates a square matrix that is n x n
# relative to the original matrix

#Recall A is a 3 x 2 matrix
#U is a 3 x 3 matrix
#Sigma = diag(s) is ???
#V.T is a 2 x 2 matrix

#All this implies that Sigma has to be a 3 x 2 matrix in order to reconstruct a 3 x 2 matrix (A)


#After creating the square diagonal matrix, the sizes of the matrices
# are relative to the original 

