# Example: Using scipy.linalg.solve() to solve SLEs

In [2]:
#import NumPy as np, along with linalg from scipy

import numpy as np
from scipy import linalg

In [3]:
#create the coefficients matrix as a NumPy array and call it A

A = np.array([[3, 2],[2, -1],])
   

In [6]:
#Display A

A

array([[ 3,  2],
       [ 2, -1]])

In [8]:
#create the independent terms vector using a NumPy array called b. To make it a column vector with two 
# lines, you use .reshape((2, 1))

b = np.array([12, 1]).reshape((2, 1))

In [9]:
#Display b

b

array([[12],
       [ 1]])

In [10]:
#call linalg.solve() to solve the linear system 
#characterized by A and b, with the result 
#stored in x, which is printed. 
#Note that solve() returns the solution with floating-point components, even though all the elements of the original arrays are integers

x = linalg.solve(A, b)

In [11]:
#Print x
x

array([[2.],
       [3.]])

# Example: Using a Model to Solve a SLE involving a Meal Plan

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
A = np.array([[1, 9, 2, 1, 1],[10, 1, 2, 1, 1],
[1, 0, 5, 1, 1],[2, 1, 1, 2, 9],[2, 1, 2, 13, 2],])

In [ ]:
#Create an array and reshape as a 5 by 1 vector

b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))

In [ ]:
x = linalg.solve(A, b)

In [ ]:
x

In [ ]:
#The solution above indicates that a balanced diet should include 
# 10 units of food 1, 10 units of food 2, 20 units of food 3, 
# 20 units of food 4, and 10 units of food 5

# How to find the inverse of a given matrix in Python

In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)

In [ ]:
# invert matrix A and store in object B
B = inv(A)
print(B)


In [ ]:
# dot multiply A and B (the inverse of A)
I = A.dot(B)
print(I)

In [ ]:
#The dot multiplication above produces an identity matrix (or the equivalent of 1 in matrix world)

# How to find the determinant of a matrix with Python

In [ ]:
#The determinant of a square matrix A, written as det(A) is a scalar representation of the volume of the matrix

#The determinant describes the relative geometry of the vectors that make up the
#rows of the matrix. More specifically, the determinant of a matrix A tells you the
#volume of a box with sides given by rows of A.

# import relevant libraries including det from numpy.linalg
from numpy import array
from numpy.linalg import det

# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

print(A)



In [ ]:
# calculate determinant of A and assign to object B
B = det(A)
print(B)

In [ ]:
#The determinant is typically defined for square matrices and it is a single number

# Example: Using Matrix Inverse to Solve Ax = b

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
A = np.array([[1, 9, 2, 1, 1],[10, 1, 2, 1, 1],
[1, 0, 5, 1, 1],[2, 1, 1, 2, 9],[2, 1, 2, 13, 2],])

In [ ]:
#Create an array and reshape as a 5 by 1 vector

b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))

In [ ]:
#Create the inverse of A

A_inv = linalg.inv(A)

In [ ]:
#Display A_inv (the inverse of A)

A_inv

In [ ]:
#A_inv is a 5X5 matrix/system so it can dot multiply b (a 5X1 vector) to produce a 5X1 vector x

x = A_inv.dot(b)

In [ ]:
x

In [ ]:
#Find the dot product of the inverse of A and vector b

y = A_inv @ b

In [ ]:
y

# Example: Solving SLEs Using QR Decomposition

In [12]:
""" QR decomposition with scipy """ 
import scipy.linalg as linalg 
import numpy as np # same matrix A and B as in LU decomposition 


In [13]:
A = np.array([ [2., 1., 1.], [1., 3., 2.], [1., 0., 0]]) 


In [14]:
B = np.array([4., 5., 6.]) 


In [15]:
Q, R = linalg.qr(A) # QR decomposition with qr function 
Q

array([[-0.81649658,  0.27602622, -0.50709255],
       [-0.40824829, -0.89708523,  0.16903085],
       [-0.40824829,  0.34503278,  0.84515425]])

In [19]:
y = np.dot(Q.T, B) # Let y=Q'.B using matrix multiplication 


In [ ]:
x = linalg.solve(R, y) # Solve Rx=y 


In [ ]:
print x

In [ ]:
#How to find the pseudoinverse of a non-square matrix using Python

In [ ]:
#Import relevant libraries and pinv from numpy.linalg

#pseudoinverse
from numpy import array
from numpy.linalg import pinv
# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)


In [ ]:
# calculate pseudoinverse of non-square matrix A and assign to object B
B = pinv(A)
print(B)

# Example: Solving SLEs with SVD + Pseudoinverse

In [ ]:
#We can use SVD to find approximate solutions for real-world problems. 
#In this example, we use the Boston house-prices dataset. 

#The house-prices data matrix A contains 506 rows (representing individual houses), 
# and 13 columns (each describing a different characteristic of the houses). 

#So A is a 506 X 13 matrix/ system

#Some of these 13 features include:

#Per capita crime rate by town
#The average number of rooms per dwelling
#Weighted distances to five Boston employment centers

In [ ]:
#Import relevant libraries and datasets from sklearn

from sklearn import datasets
from sklearn.model_selection import train_test_split



In [ ]:
# load the boston house data

data = datasets.load_boston()


In [ ]:
data

In [ ]:
# extract the input data matrix and the target values
A = data.data
b = data.target

In [ ]:
A

In [ ]:
# Step 1: append a columns of 1s (these are the biases)
A = np.column_stack([np.ones(A.shape[0]), A])

In [ ]:
A

In [ ]:
# Step 2: split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(A, b, test_size=0.50, random_state=42)

In [ ]:
# Step 3: calculate the economy SVD for the data matrix A
U,S,Vt = np.linalg.svd(X_train, full_matrices=False)

In [ ]:
# Step 4: solve Ax = b for the best possible approximate solution in terms of least squares
x_hat = Vt.T @ np.linalg.inv(np.diag(S)) @ U.T @ y_train

In [ ]:
#Step 5: print x_hat

x_hat