# Example Basic Vector Math in Python

In [1]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


In [2]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)




[1 2 3]


In [3]:
# define second vector
b = array([1, 2, 3])
print(b)

[1 2 3]


In [4]:
# add vectors
c = a + b
print(c)

[2 4 6]


In [5]:
# vector subtraction

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b


[1 2 3]
[0.5 0.5 0.5]


In [6]:
# vector multiplication

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)


[1 2 3]
[1 2 3]
[1 4 9]


In [7]:
# vector element-wise division in Python


from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)


[1 2 3]
[1 2 3]
[1. 1. 1.]


In [8]:
# vector dot product in Python

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([5, 7, 9])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

#this is a dot b= (1*5)+(2*7)+(3*9)=5+14+27=46


#dot product always give you a single number! 

[1 2 3]
[5 7 9]
46


In [9]:
# vector-scalar multiplication in Python

from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


In [10]:
#Example - Computing Norms in Python:

#

In [11]:
# Case 1: vector L1 norm

from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a,1)  ## 1 indicates L1 norm since default is always L2 norm  

[1 2 3]


In [12]:
#Print L1 norm of vector a

l1

6.0

In [13]:
#Code to normalize vector a with its L1 norm

Normalised_a = a/l1 ##to normalize a vector yoy divide the vector by its L1 norm

In [14]:
#Print L1 normalized a

print(Normalised_a)

[0.16666667 0.33333333 0.5       ]


In [15]:
#Case 2: Computing vector L2 norm (also known as Euclidean Norm) as it is 
# calculated as the Euclidean distance from the origin


from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)   ##L2 norm is default so no parameter automatically does L2 norm
print(l2)


[1 2 3]
3.7416573867739413


In [16]:
#Case 3: Computing vector max norm in Python

from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)


#Max norm is also used as a regularization in machine learning, such as on neural network
# weights, called max norm regularization

[1 2 3]
3.0


# Working with a Matrix and Matrices in Python

In [17]:
#We can represent a matrix in Python using a two-dimensional NumPy array

In [18]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

#matrix is a 2D array of numbers 

#matrix are with capital letters, vectors are lowercase 

[[1 2 3]
 [4 5 6]]


In [19]:
#Matrix Arithmetic

In [20]:
# matrix addition in Python
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# add matrices
C = A + B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [21]:
# matrix subtraction in Python
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)
# subtract matrices
C = A - B
print(C)


[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [22]:
#Two matrices with the same size can be multiplied together, and this is often called element-wise
#matrix multiplication or the Hadamard product


# matrix-matrix Hadamard product
#element-wise product

from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
# multiply matrices to obtain Hadamard product
C = A * B
print(C)

[[ 1  4  9]
 [16 25 36]]


In [24]:
# matrix-matrix dot product in Python

#dot product matrices musthave same dimensions
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [25]:
# multiply matrices
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [26]:
# multiply matrices with @ operator
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]


In [27]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)



[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]


In [28]:
# multiply to obtain matrix-vector product 
C = A.dot(B)
print(C)

[1.5 3.5 5.5]


In [29]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

# define scalar
b = 0.5
print(b)


[[1 2]
 [3 4]
 [5 6]]
0.5


In [30]:
# multiply to obtain matrix-scalar multiplication
C = A * b
print(C)

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [31]:
# matrix element-wise division in Python

from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# Transpose matrix of a matrix in Python
from numpy import array
# define matrix A
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)



[[1 2]
 [3 4]
 [5 6]]


In [33]:
# Calculate transpose of Matrix A
# Use the T attribute to compute the transpose of A

C = A.T
print(C)

[[1 3 5]
 [2 4 6]]


#### Quiz 2 Questions

1. Divide the Euclidean norm of vector [1, 2, 5, 10] by the sum of its max norm and L1 norm.

In [34]:
## Divide the Euclidean norm of vector [1, 2, 5, 10] by the sum of its max norm and L1 norm.

from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 5, 10])
print(a)
#euclidean norm
eucnorm=norm(a,2)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)
l1norm = norm(a,1)
print(l1norm)


ans=eucnorm/(maxnorm+l1norm)
ans

[ 1  2  5 10]
10.0
18.0


0.40720550896397784

2. What is the difference between the max norm of [-90,-104,60, 23,56] and the L1 norm of the vector resulting from the element-wise product of the vectors [1,5,-3] and [1,2,4].

In [35]:
b= array([-90,-104,60, 23,56])

c=array([1,5,-3])
d=array([1,2,4])

eleprod=c*d
print(eleprod)

l1res=norm(eleprod,1)
print(l1res)

maxnormb= norm(b, inf)
print(maxnormb)

maxnormb-l1res

[  1  10 -12]
23.0
104.0


81.0

## In class activity 2/7

3. Find the L2 euclidean norm of following
    - [-3,6,7]
    - [3,2,1]
4. Normalize with their l2 norm --> so do vector/l2norm
    - [-1,4,8]
    - [3,5,1]
5. Find l1 norm of 
    - [2,3,-5]
    - [1,6,9]
6. normalize with their l1 norms
7. find the max norm of all above
    - 7
    - 3
    - 8
    - 5
    - 3
    - 9

In [6]:
## 3. Find the L2 euclidean norm of following

a= array([-3,6,7])
b= array([3,2,1])

anorm=norm(a,2)
print(anorm)
bnorm=norm(b,2)
print(bnorm)

9.695359714832659
3.7416573867739413


In [14]:
## 4.Normalize with their l2 norm --> so do vector/l2norm

c=array([-1,4,8])
d=array([3,5,1])

cnorm=norm(c,2)
print(c/cnorm) ##vector divided by l2 norm == normalize with their l2 norm
dnorm=norm(d,2)
print(d/dnorm)

[-0.11111111  0.44444444  0.88888889]
[0.50709255 0.84515425 0.16903085]


In [19]:
## 5. Find l1 norm 


e= array([2,3,-5])
f=array([1,6,9])

enorm=norm(d,1)
print(enorm)
fnorm=norm(f,1)
print(fnorm)

9.0
16.0


In [18]:
## 6. normalize with their l1 norms

print("a", a/norm(a,1))
print("b", b/norm(b,1))
print("c", c/norm(c,1))
print("d", d/norm(d,1))
print("e", e/norm(e,1))
print("f", f/norm(f,1))

a [-0.1875  0.375   0.4375]
b [0.5        0.33333333 0.16666667]
c [-0.07692308  0.30769231  0.61538462]
d [0.33333333 0.55555556 0.11111111]
e [ 0.2  0.3 -0.5]
f [0.0625 0.375  0.5625]


7. Find Euclidean distance between A and B :
- A(1,2) B(3,2)
- A(3,5) B(2,6)

In [20]:
import numpy as np
np.sqrt((1-3)**2+ (2-2)**2)

2.0

In [21]:
np.sqrt((3-2)**2+ (5-6)**2)

1.4142135623730951

8. Given following points as part of k means clustering exercise, fine an estimate of the coordinates of a resulting centroid:

- A(1,2)
- B(-3,1)
- C(3,7)
- D(-2,5)

In [24]:
xcoord= (1+-3+3+-2)/4
ycoord=(2+1+7+5)/4
print(xcoord,ycoord) #(-0.25,3.75)

-0.25 3.75


9. (Manual) Standardization of a feature (Standard Scaler) (5 mins):
    - If a feature Age has the following entries, standardize them using StandardScaler
    - Age = (41, 25, 20)

In [25]:
from sklearn.preprocessing import StandardScaler

In [36]:
age= array([41, 25, 20])
mu=np.mean(age)
sigma=np.std(age)

standardizedage= (age-mu)/sigma #x-mean/stdev
print(standardizedage)

[ 1.37699742 -0.40937761 -0.96761981]


10. (Manual) Normalization of a feature (Min-Max Values) (5 mins):
    - If a feature Age has the following entries, normalize them using Min-Max Values
    - Age = (41,25,20)

In [39]:
age= array([41, 25, 20])
(a-20)/(41-20) ##x-minx/(maxx-minx)

array([-1.0952381 , -0.66666667, -0.61904762])

### Exam 1 

In [38]:
#If you scale vector p = [2.4, 2.6, 0.5] with the max norm of vector j = [2, 5, 10] what is the z-axis coordinate of the new (scaled) vector?
p = array([2.4, 2.6, 0.5])
p*10

array([24., 26.,  5.])

In [39]:
#If you normalize the vector p = [2.4, 2.6, 0.5] by its max norm, what is the z-axis coordinate of the new (normalized) vector
p/2.6

array([0.92307692, 1.        , 0.19230769])

In [40]:
#Perform element-wise division of vector d = [2 , 4, 8] by vector f = [2, 2, 4]and find the sum of all the x, y and z-axis coordinates of the new vector.
d = array([2 , 4, 8])
f = array([2, 2, 4])
d/f

array([1., 2., 2.])

In [41]:
#Add the Euclidean norm of vector h = [1, 3, 5] to the L1 norm of vector c = [-2, -3, 6].
h =array( [1, 3, 5])
c=array([-2, -3, 6])

eu=norm(h,2)
l1=norm(c,1)
eu+l1

16.916079783099615

In [42]:
#Given vector f = [1,4,8], vector b = [2,3,4] and vector y = [3,-3, 4] in 3 what is the sum of the values/coordinates of the vector resulting from the sum of f, b and y?
f= array([1,4,8])
b=array( [2,3,4])
y=array([3,-3, 4])
f+b+y

array([ 6,  4, 16])

In [43]:
6+4+16

26

In [44]:
3.16228/4.123106

0.76696548669862

In [57]:


a= array([6,5,6,3])
n=(a-3)/(6-3) ##x-minx/(maxx-minx)
n


array([1.        , 0.66666667, 1.        , 0.        ])

In [56]:
a= array([27,35,15,5])
n=(a-5)/(35-5) ##x-minx/(maxx-minx)
n

array([0.73333333, 1.        , 0.33333333, 0.        ])

In [58]:
a= array([29,35,12,0])
n=(a-0)/(35-0) ##x-minx/(maxx-minx)
n


array([0.82857143, 1.        , 0.34285714, 0.        ])