# February 2, 2023

# Example Basic Vector Math in Python

In [44]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)



[1 2 3]


In [45]:
# define second vector
b = array([1, 2, 3])
print(b)

[1 2 3]


In [46]:
# add vectors
c = a + b
print(c)

[2 4 6]


In [49]:
# vector subtraction

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [48]:
a-b

array([0.5, 1.5, 2.5])

In [50]:
# vector element-wise multiplication in Python

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)



[1 2 3]
[1 2 3]


In [51]:
# multiply vectors
c = a * b
print(c)

[1 4 9]


In [52]:
# vector element-wise division in Python


from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)


[1 2 3]
[1 2 3]
[1. 1. 1.]


In [53]:
# vector dot product in Python

from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)


[1 2 3]
[1 2 3]
14


In [54]:
from numpy import array
# define first vector
a = array([6,5])
print(a)
# define second vector
b = array([1, 2])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[6 5]
[1 2]
16


In [ ]:
# vector-scalar multiplication in Python

from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

# Example - Computing Norms in Python:

In [55]:
# Case 1: vector L1 norm

from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
L1_norm = norm(a,1)

[1 2 3]


In [56]:
#Print L1 norm of vector a

L1_norm

6.0

In [57]:
#Code to normalize vector a with its L1 norm

Normalised_a = a/L1_norm

In [58]:
#Print L1 normalized a

print(Normalised_a)

[0.16666667 0.33333333 0.5       ]


In [59]:
#Print L1 normalized a

Normalised_a

array([0.16666667, 0.33333333, 0.5       ])

In [60]:
#Case 2: Computing vector L2 norm (also known as Euclidean Norm) as it is 
# calculated as the Euclidean distance from the origin


from numpy import array
from numpy.linalg import norm
# define vector
b = array([1, 2, 3])
print(b)
# calculate norm
L2_norm = norm(b)
print(L2_norm)


[1 2 3]
3.7416573867739413


In [61]:
#You can also compute the L2 norm for vector b by norm (a, 2)

L2_norm = norm (b, 2)

In [62]:
print (L2_norm)

3.7416573867739413


In [63]:
#We can then normalize vector a by its L2 norm as follows;

Normalized_b = b/L2_norm


In [64]:
#Print the normalized values for vector b

Normalized_b

array([0.26726124, 0.53452248, 0.80178373])

In [65]:
#Print the normalized values for b directly

b/L2_norm

array([0.26726124, 0.53452248, 0.80178373])

In [66]:
#Case 3: Computing vector max norm in Python

from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)


[1 2 3]
3.0


In [67]:
#Case 3: Computing vector max norm in Python

from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
j = array([-600, 52, 13])
print(j)
# calculate norm
maxnorm_2 = norm(j, inf)
print(maxnorm_2)

[-600   52   13]
600.0


In [68]:
#Max norm is also used as a regularization in machine learning, such as on neural network
# weights, called max norm regularization

#Note that the absolute value of the entries is taken before finding the maximum value

# Working with a Matrix and Matrices in Python

In [ ]:
#A Matrix is a two-dimensional array of numbers

#We can represent a matrix in Python using a two-dimensional NumPy array

In [69]:
# One way to create a matrix in Python

from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [ ]:
#Matrix Arithmetic

In [70]:
#Case 1: matrix addition in Python
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# add matrices
C = A + B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [71]:
# Case 2: matrix subtraction in Python
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)
# subtract matrices
C = A - B
print(C)


[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [72]:
#Two matrices with the same size can be multiplied together, and this is often called element-wise
#matrix multiplication or the Hadamard product


#Case 3: matrix-matrix Hadamard product (element-wise matrix-matrix product)

from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [73]:
# multiply matrices to obtain Hadamard product
C = A * B
print(C)

[[ 1  4  9]
 [16 25 36]]


In [74]:
#Case 4: matrix-matrix dot product in Python
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [75]:
# Compute dot product of matrices A and B and assign to matrix object C
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [76]:
# multiply matrices with @ operator
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]


# Matrix- Vector Math

In [ ]:
#For Matrix-Vector multiplication, the number of columns in the Matrix MUST match the number of entries in the vector

#The result is a Vector with the same number of rows as the parent Matrix

In [78]:
# matrix-vector multiplication

from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
b = array([0.5, 0.5])
print(b)



[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]


In [79]:
# multiply to obtain matrix-vector product 
C = A.dot(B)
print(C)

[1.5 3.5 5.5]


In [ ]:
#Note:

#1.Matrix - Vector multiplication uses the same syntax as Matrix-Matrix dot product

# 2. Python will perform Matrix-Vector multiplication
# If the dimensions do not allow for Matrix-Matrix dot product
# but the conditions for Matrix-Vector multiplication is met
# i.e. number of matrix columns match number of entries in vector

In [ ]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

# define scalar
b = 0.5
print(b)


In [ ]:
# multiply to obtain matrix-scalar multiplication
C = A * b
print(C)

In [ ]:
# matrix element-wise division in Python

from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

In [ ]:
# Transpose matrix of a matrix in Python
from numpy import array
# define matrix A
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)



In [ ]:
# Calculate transpose of Matrix A
# Use the T attribute to compute the transpose of A

C = A.T
print(C)