# Homework 2 - Part 3

In [1]:
#Student Name: Julia Troni

#Student ID: 109280095

In [2]:
#Use the following information to answer Question 1 through Question 5

In [3]:
#RUN THIS CELL FIRST before you answer Questions 1 - 5

from numpy import array
from numpy.linalg import norm

#Suppose we create/define the following arrays

A1 = array([1,-3,4,5])

A2 = array([3,4,5,7])

A3 = array([
[1, 2],
[3, 4],
[5, 6]])

A4 = array([
[1, 2],
[3, 4]])

A5 = array([
[1, 2],
[3, 4],
[5, 6]])

A6 = array([0.5, 0.5])

A7 = array([[3,-5],
           [16,8],
            [21,23]])

In [4]:
#Question 1:

#Write Python code below to find the element-wise division of A3 by A7
element_division= A3/A7

print(element_division)


[[ 0.33333333 -0.4       ]
 [ 0.1875      0.5       ]
 [ 0.23809524  0.26086957]]


In [5]:
#Question 2:

#Write Python code below to find the transpose of A7

transA7= A7.T

print(transA7)

[[ 3 16 21]
 [-5  8 23]]


In [6]:
#Question 3:

#Write Python code below to divide the transpose of A7 by 5

print(transA7/5)

[[ 0.6  3.2  4.2]
 [-1.   1.6  4.6]]


In [7]:
#Question 4:

#Write Python code below to find the vector dot product of A1 and A2

vecdot12= A1.dot(A2)

print(vecdot12)

46


In [8]:
#Question 5:

#Write Python code below to divide the l1 norm of A1 by the Euclidean norm of A2.

#Do not assign the L1/ Euclidean norms to any object before the division


l1diveu= norm(A1,1)/norm(A2,2)

print(l1diveu)

1.3065491598369756


In [9]:
#RUN THIS CELL FIRST before you answer Questions 6 - 10

from numpy import array
from numpy.linalg import norm

#Suppose we create/define the following arrays

# matrix-matrix Hadamard product
#element-wise product



B1 = array([
[1, 2, 3],
[4, 5, 6]])



B2 = array([
[1, 2, 3],
[4, 5, 6]])


B3 = array([[2,3],[5,1],[3,4]])

In [10]:
#Question 6

#Write Python code below to find the Hadamard product of B1 and B2

#Do not assign the product to an object

print(B1*B2)


[[ 1  4  9]
 [16 25 36]]


In [11]:
#Question 7

#Write Python code below to subtract B2 from B1

print(B1-B2)

[[0 0 0]
 [0 0 0]]


In [12]:
#Question 8

#Write Python code below to find the transpose of B2

print(B2.T)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
#Question 9

#Write Python code below to find the matrix-matrix dot product of B2 and B3

print(B2.dot(B3))

[[21 17]
 [51 41]]


In [14]:
#Question 10

#Write Python code below to divide B1 by 0.7

print(B1/0.7)


[[1.42857143 2.85714286 4.28571429]
 [5.71428571 7.14285714 8.57142857]]
